# Generated by Django 3.1.6 on 2021-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
