# Generated by Django 3.1.6 on 2021-02-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_auto_20210214_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switches', to='iot.device'),
        ),
    ]
