# Generated by Django 3.1.6 on 2021-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20210214_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='port_number',
            field=models.IntegerField(default=None, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
