# Generated by Django 3.1.6 on 2021-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20210214_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='port_number',
            field=models.IntegerField(default=None, max_length=3),
        ),
    ]
