# Generated by Django 3.1.6 on 2021-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20210214_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='port_number',
            field=models.IntegerField(default=None),
        ),
    ]
