# Generated by Django 3.1.6 on 2021-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20210214_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
    ]
